// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package restful

import (
	"github.com/blackhorseya/assessment-bito/app/domain/match/biz"
	"github.com/blackhorseya/assessment-bito/app/domain/match/repo/player"
	"github.com/blackhorseya/assessment-bito/pkg/adapterx"
	"github.com/blackhorseya/assessment-bito/pkg/transports/httpx"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

import (
	_ "github.com/blackhorseya/assessment-bito/adapter/api/docs"
)

// Injectors from wire.go:

func NewMemory(v *viper.Viper) (adapterx.Servicer, error) {
	server, err := httpx.NewServer()
	if err != nil {
		return nil, err
	}
	iPlayerRepo := player.NewPlayerRepoWithMemory()
	iMatchBiz := biz.NewMatchBiz(iPlayerRepo)
	servicer := newService(server, iMatchBiz)
	return servicer, nil
}

func NewRBTree(v *viper.Viper) (adapterx.Servicer, error) {
	server, err := httpx.NewServer()
	if err != nil {
		return nil, err
	}
	iPlayerRepo := player.NewPlayerRepoWithRBTree()
	iMatchBiz := biz.NewMatchBiz(iPlayerRepo)
	servicer := newService(server, iMatchBiz)
	return servicer, nil
}

// wire.go:

var providerSet = wire.NewSet(httpx.NewServer, biz.ProvideMatchBiz)
