/*
 * Bito API
 * Bito api swagger
 *
 * OpenAPI spec version: 0.1.0
 * Contact: blackhorseya@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * Generator version: 7.5.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "/api";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/v1/players", () => {

        // Request No. 1: 
        {
            let url = BASE_URL + `/v1/players`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2: 
        {
            let url = BASE_URL + `/v1/players`;
            // TODO: edit the parameters of the request body.
            let body = {"age": "integer", "gender": "model.gender", "height": "integer", "name": "string", "numsOfWantedDates": "integer"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Created": (r) => r.status === 201
            });
        }
    });

    group("/v1/pairs", () => {

        // Request No. 1: 
        {
            let url = BASE_URL + `/v1/pairs`;
            // TODO: edit the parameters of the request body.
            let body = {"leftId": "string", "rightId": "string"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Created": (r) => r.status === 201
            });
        }
    });

    group("/v1/players/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let n = 'TODO_EDIT_THE_N'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1: 
        {
            let url = BASE_URL + `/v1/players/${id}?n=${n}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2: 
        {
            let url = BASE_URL + `/v1/players/${id}`;
            let request = http.del(url);

            check(request, {
                "No Content": (r) => r.status === 204
            });
        }
    });

}
